---
- name: Remove duplicate or old Docker list files
  file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop:
    - docker.list
    - download_docker_com_linux_ubuntu.list

- name: Create directory for Docker keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Install prerequisite dependencies
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, python3-pip]
    update_cache: yes
    state: present

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository with signed-by key
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker Engine and Compose Plugin
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
    state: present

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Create shared network for Traefik
  docker_network:
    name: web_net
    state: present